; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --global-value-regex "x" --version 4
; RUN: opt < %s -S -passes=hwasan -mtriple=aarch64-linux-gnu -hwasan-globals=0 | FileCheck %s --check-prefixes=NOGLOB
; RUN: opt < %s -S -passes=hwasan -mtriple=aarch64-linux-gnu -hwasan-globals=1 -hwasan-opt-globals=0 | FileCheck %s --check-prefixes=CHECK,UNOPT
; RUN: opt < %s -S -passes=hwasan -mtriple=aarch64-linux-gnu -hwasan-globals=1 -hwasan-opt-globals=1 | FileCheck %s --check-prefixes=CHECK,OPT

target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"

@x = dso_local global i32 0, align 4
@arr = dso_local global [10 x i32] zeroinitializer, align 4

;.
; NOGLOB: @x = dso_local global i32 0, align 4
;.
; CHECK: @x = alias i32, inttoptr (i64 add (i64 ptrtoint (ptr @x.hwasan to i64), i64 5260204364768739328) to ptr)
;.
define dso_local noundef i32 @_Z3tmpv() sanitize_hwaddress {
; NOGLOB-LABEL: define dso_local noundef i32 @_Z3tmpv(
; NOGLOB-SAME: ) #[[ATTR0:[0-9]+]] {
; NOGLOB-NEXT:  entry:
; NOGLOB-NEXT:    [[TMP0:%.*]] = load i32, ptr @x, align 4
; NOGLOB-NEXT:    ret i32 [[TMP0]]
;
; UNOPT-LABEL: define dso_local noundef i32 @_Z3tmpv(
; UNOPT-SAME: ) #[[ATTR0:[0-9]+]] {
; UNOPT-NEXT:  entry:
; UNOPT-NEXT:    [[TMP0:%.*]] = load i64, ptr @__hwasan_tls, align 8
; UNOPT-NEXT:    [[TMP1:%.*]] = or i64 [[TMP0]], 4294967295
; UNOPT-NEXT:    [[HWASAN_SHADOW:%.*]] = add i64 [[TMP1]], 1
; UNOPT-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[HWASAN_SHADOW]] to ptr
; UNOPT-NEXT:    [[TMP3:%.*]] = lshr i64 ptrtoint (ptr @x to i64), 56
; UNOPT-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i8
; UNOPT-NEXT:    [[TMP5:%.*]] = and i64 ptrtoint (ptr @x to i64), 72057594037927935
; UNOPT-NEXT:    [[TMP6:%.*]] = lshr i64 [[TMP5]], 4
; UNOPT-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[TMP2]], i64 [[TMP6]]
; UNOPT-NEXT:    [[TMP8:%.*]] = load i8, ptr [[TMP7]], align 1
; UNOPT-NEXT:    [[TMP9:%.*]] = icmp ne i8 [[TMP4]], [[TMP8]]
; UNOPT-NEXT:    br i1 [[TMP9]], label [[TMP10:%.*]], label [[TMP11:%.*]], !prof [[PROF4:![0-9]+]]
; UNOPT:       10:
; UNOPT-NEXT:    call void @llvm.hwasan.check.memaccess.shortgranules(ptr [[TMP2]], ptr @x, i32 2)
; UNOPT-NEXT:    br label [[TMP11]]
; UNOPT:       11:
; UNOPT-NEXT:    [[TMP12:%.*]] = load i32, ptr @x, align 4
; UNOPT-NEXT:    ret i32 [[TMP12]]
;
; OPT-LABEL: define dso_local noundef i32 @_Z3tmpv(
; OPT-SAME: ) #[[ATTR0:[0-9]+]] {
; OPT-NEXT:  entry:
; OPT-NEXT:    [[TMP0:%.*]] = load i32, ptr @x, align 4
; OPT-NEXT:    ret i32 [[TMP0]]
;
entry:
  %0 = load i32, ptr @x, align 4
  ret i32 %0
}

define i32 @test_inbounds_array_load() sanitize_hwaddress {
; NOGLOB-LABEL: define i32 @test_inbounds_array_load(
; NOGLOB-SAME: ) #[[ATTR0]] {
; NOGLOB-NEXT:  entry:
; NOGLOB-NEXT:    [[PTR:%.*]] = getelementptr inbounds [10 x i32], ptr @arr, i64 0, i64 3
; NOGLOB-NEXT:    [[TMP0:%.*]] = load i32, ptr [[PTR]], align 4
; NOGLOB-NEXT:    ret i32 [[TMP0]]
;
; UNOPT-LABEL: define i32 @test_inbounds_array_load(
; UNOPT-SAME: ) #[[ATTR0]] {
; UNOPT-NEXT:  entry:
; UNOPT-NEXT:    [[TMP0:%.*]] = load i64, ptr @__hwasan_tls, align 8
; UNOPT-NEXT:    [[TMP1:%.*]] = or i64 [[TMP0]], 4294967295
; UNOPT-NEXT:    [[HWASAN_SHADOW:%.*]] = add i64 [[TMP1]], 1
; UNOPT-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[HWASAN_SHADOW]] to ptr
; UNOPT-NEXT:    [[PTR:%.*]] = getelementptr inbounds [10 x i32], ptr @arr, i64 0, i64 3
; UNOPT-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[PTR]] to i64
; UNOPT-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 56
; UNOPT-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i8
; UNOPT-NEXT:    [[TMP6:%.*]] = and i64 [[TMP3]], 72057594037927935
; UNOPT-NEXT:    [[TMP7:%.*]] = lshr i64 [[TMP6]], 4
; UNOPT-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP2]], i64 [[TMP7]]
; UNOPT-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP8]], align 1
; UNOPT-NEXT:    [[TMP10:%.*]] = icmp ne i8 [[TMP5]], [[TMP9]]
; UNOPT-NEXT:    br i1 [[TMP10]], label [[TMP11:%.*]], label [[TMP12:%.*]], !prof [[PROF4]]
; UNOPT:       11:
; UNOPT-NEXT:    call void @llvm.hwasan.check.memaccess.shortgranules(ptr [[TMP2]], ptr [[PTR]], i32 2)
; UNOPT-NEXT:    br label [[TMP12]]
; UNOPT:       12:
; UNOPT-NEXT:    [[TMP13:%.*]] = load i32, ptr [[PTR]], align 4
; UNOPT-NEXT:    ret i32 [[TMP13]]
;
; OPT-LABEL: define i32 @test_inbounds_array_load(
; OPT-SAME: ) #[[ATTR0]] {
; OPT-NEXT:  entry:
; OPT-NEXT:    [[PTR:%.*]] = getelementptr inbounds [10 x i32], ptr @arr, i64 0, i64 3
; OPT-NEXT:    [[TMP0:%.*]] = load i32, ptr [[PTR]], align 4
; OPT-NEXT:    ret i32 [[TMP0]]
;
entry:
  %ptr = getelementptr inbounds [10 x i32], ptr @arr, i64 0, i64 3
  %0 = load i32, ptr %ptr, align 4
  ret i32 %0
}

define i32 @test_out_of_bounds_array_load() sanitize_hwaddress {
; NOGLOB-LABEL: define i32 @test_out_of_bounds_array_load(
; NOGLOB-SAME: ) #[[ATTR0]] {
; NOGLOB-NEXT:  entry:
; NOGLOB-NEXT:    [[PTR:%.*]] = getelementptr [10 x i32], ptr @arr, i64 0, i64 15
; NOGLOB-NEXT:    [[TMP0:%.*]] = load i32, ptr [[PTR]], align 4
; NOGLOB-NEXT:    ret i32 [[TMP0]]
;
; CHECK-LABEL: define i32 @test_out_of_bounds_array_load(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr @__hwasan_tls, align 8
; CHECK-NEXT:    [[TMP1:%.*]] = or i64 [[TMP0]], 4294967295
; CHECK-NEXT:    [[HWASAN_SHADOW:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[HWASAN_SHADOW]] to ptr
; CHECK-NEXT:    [[PTR:%.*]] = getelementptr [10 x i32], ptr @arr, i64 0, i64 15
; CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[PTR]] to i64
; CHECK-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 56
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i8
; CHECK-NEXT:    [[TMP6:%.*]] = and i64 [[TMP3]], 72057594037927935
; CHECK-NEXT:    [[TMP7:%.*]] = lshr i64 [[TMP6]], 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP2]], i64 [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP8]], align 1
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i8 [[TMP5]], [[TMP9]]
; CHECK-NEXT:    br i1 [[TMP10]], label [[TMP11:%.*]], label [[TMP12:%.*]], !prof [[PROF4:![0-9]+]]
; CHECK:       11:
; CHECK-NEXT:    call void @llvm.hwasan.check.memaccess.shortgranules(ptr [[TMP2]], ptr [[PTR]], i32 2)
; CHECK-NEXT:    br label [[TMP12]]
; CHECK:       12:
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[PTR]], align 4
; CHECK-NEXT:    ret i32 [[TMP13]]
;
entry:
  %ptr = getelementptr [10 x i32], ptr @arr, i64 0, i64 15
  %0 = load i32, ptr %ptr, align 4
  ret i32 %0
}

define i32 @test_variable_index_array_load(i64 %idx) sanitize_hwaddress {
; NOGLOB-LABEL: define i32 @test_variable_index_array_load(
; NOGLOB-SAME: i64 [[IDX:%.*]]) #[[ATTR0]] {
; NOGLOB-NEXT:  entry:
; NOGLOB-NEXT:    [[TMP0:%.*]] = load i64, ptr @__hwasan_tls, align 8
; NOGLOB-NEXT:    [[TMP1:%.*]] = or i64 [[TMP0]], 4294967295
; NOGLOB-NEXT:    [[HWASAN_SHADOW:%.*]] = add i64 [[TMP1]], 1
; NOGLOB-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[HWASAN_SHADOW]] to ptr
; NOGLOB-NEXT:    [[PTR:%.*]] = getelementptr inbounds [10 x i32], ptr @arr, i64 0, i64 [[IDX]]
; NOGLOB-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[PTR]] to i64
; NOGLOB-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 56
; NOGLOB-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i8
; NOGLOB-NEXT:    [[TMP6:%.*]] = and i64 [[TMP3]], 72057594037927935
; NOGLOB-NEXT:    [[TMP7:%.*]] = lshr i64 [[TMP6]], 4
; NOGLOB-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP2]], i64 [[TMP7]]
; NOGLOB-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP8]], align 1
; NOGLOB-NEXT:    [[TMP10:%.*]] = icmp ne i8 [[TMP5]], [[TMP9]]
; NOGLOB-NEXT:    br i1 [[TMP10]], label [[TMP11:%.*]], label [[TMP12:%.*]], !prof [[PROF2:![0-9]+]]
; NOGLOB:       11:
; NOGLOB-NEXT:    call void @llvm.hwasan.check.memaccess.shortgranules(ptr [[TMP2]], ptr [[PTR]], i32 2)
; NOGLOB-NEXT:    br label [[TMP12]]
; NOGLOB:       12:
; NOGLOB-NEXT:    [[TMP13:%.*]] = load i32, ptr [[PTR]], align 4
; NOGLOB-NEXT:    ret i32 [[TMP13]]
;
; CHECK-LABEL: define i32 @test_variable_index_array_load(
; CHECK-SAME: i64 [[IDX:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr @__hwasan_tls, align 8
; CHECK-NEXT:    [[TMP1:%.*]] = or i64 [[TMP0]], 4294967295
; CHECK-NEXT:    [[HWASAN_SHADOW:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[HWASAN_SHADOW]] to ptr
; CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds [10 x i32], ptr @arr, i64 0, i64 [[IDX]]
; CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[PTR]] to i64
; CHECK-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 56
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i8
; CHECK-NEXT:    [[TMP6:%.*]] = and i64 [[TMP3]], 72057594037927935
; CHECK-NEXT:    [[TMP7:%.*]] = lshr i64 [[TMP6]], 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP2]], i64 [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP8]], align 1
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i8 [[TMP5]], [[TMP9]]
; CHECK-NEXT:    br i1 [[TMP10]], label [[TMP11:%.*]], label [[TMP12:%.*]], !prof [[PROF4]]
; CHECK:       11:
; CHECK-NEXT:    call void @llvm.hwasan.check.memaccess.shortgranules(ptr [[TMP2]], ptr [[PTR]], i32 2)
; CHECK-NEXT:    br label [[TMP12]]
; CHECK:       12:
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[PTR]], align 4
; CHECK-NEXT:    ret i32 [[TMP13]]
;
entry:
  %ptr = getelementptr inbounds [10 x i32], ptr @arr, i64 0, i64 %idx
  %0 = load i32, ptr %ptr, align 4
  ret i32 %0
}

define void @test_inbounds_memset() sanitize_hwaddress {
; NOGLOB-LABEL: define void @test_inbounds_memset(
; NOGLOB-SAME: ) #[[ATTR0]] {
; NOGLOB-NEXT:  entry:
; NOGLOB-NEXT:    call void @llvm.memset.p0.i64(ptr @arr, i8 0, i64 40, i1 false)
; NOGLOB-NEXT:    ret void
;
; UNOPT-LABEL: define void @test_inbounds_memset(
; UNOPT-SAME: ) #[[ATTR0]] {
; UNOPT-NEXT:  entry:
; UNOPT-NEXT:    [[TMP0:%.*]] = load i64, ptr @__hwasan_tls, align 8
; UNOPT-NEXT:    [[TMP1:%.*]] = or i64 [[TMP0]], 4294967295
; UNOPT-NEXT:    [[HWASAN_SHADOW:%.*]] = add i64 [[TMP1]], 1
; UNOPT-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[HWASAN_SHADOW]] to ptr
; UNOPT-NEXT:    [[TMP3:%.*]] = call ptr @__hwasan_memset(ptr @arr, i32 0, i64 40)
; UNOPT-NEXT:    ret void
;
; OPT-LABEL: define void @test_inbounds_memset(
; OPT-SAME: ) #[[ATTR0]] {
; OPT-NEXT:  entry:
; OPT-NEXT:    call void @llvm.memset.p0.i64(ptr @arr, i8 0, i64 40, i1 false)
; OPT-NEXT:    ret void
;
entry:
  call void @llvm.memset.p0.i64(ptr @arr, i8 0, i64 40, i1 false)
  ret void
}

define i32 @test_negative_offset() sanitize_hwaddress {
; NOGLOB-LABEL: define i32 @test_negative_offset(
; NOGLOB-SAME: ) #[[ATTR0]] {
; NOGLOB-NEXT:  entry:
; NOGLOB-NEXT:    [[PTR:%.*]] = getelementptr i32, ptr @x, i64 -1
; NOGLOB-NEXT:    [[TMP0:%.*]] = load i32, ptr [[PTR]], align 4
; NOGLOB-NEXT:    ret i32 [[TMP0]]
;
; CHECK-LABEL: define i32 @test_negative_offset(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr @__hwasan_tls, align 8
; CHECK-NEXT:    [[TMP1:%.*]] = or i64 [[TMP0]], 4294967295
; CHECK-NEXT:    [[HWASAN_SHADOW:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[HWASAN_SHADOW]] to ptr
; CHECK-NEXT:    [[PTR:%.*]] = getelementptr i32, ptr @x, i64 -1
; CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[PTR]] to i64
; CHECK-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 56
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i8
; CHECK-NEXT:    [[TMP6:%.*]] = and i64 [[TMP3]], 72057594037927935
; CHECK-NEXT:    [[TMP7:%.*]] = lshr i64 [[TMP6]], 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP2]], i64 [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP8]], align 1
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i8 [[TMP5]], [[TMP9]]
; CHECK-NEXT:    br i1 [[TMP10]], label [[TMP11:%.*]], label [[TMP12:%.*]], !prof [[PROF4]]
; CHECK:       11:
; CHECK-NEXT:    call void @llvm.hwasan.check.memaccess.shortgranules(ptr [[TMP2]], ptr [[PTR]], i32 2)
; CHECK-NEXT:    br label [[TMP12]]
; CHECK:       12:
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[PTR]], align 4
; CHECK-NEXT:    ret i32 [[TMP13]]
;
entry:
  %ptr = getelementptr i32, ptr @x, i64 -1
  %0 = load i32, ptr %ptr, align 4
  ret i32 %0
}

define i64 @test_oversized_load() sanitize_hwaddress {
; NOGLOB-LABEL: define i64 @test_oversized_load(
; NOGLOB-SAME: ) #[[ATTR0]] {
; NOGLOB-NEXT:  entry:
; NOGLOB-NEXT:    [[TMP0:%.*]] = load i64, ptr @x, align 8
; NOGLOB-NEXT:    ret i64 [[TMP0]]
;
; CHECK-LABEL: define i64 @test_oversized_load(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr @__hwasan_tls, align 8
; CHECK-NEXT:    [[TMP1:%.*]] = or i64 [[TMP0]], 4294967295
; CHECK-NEXT:    [[HWASAN_SHADOW:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[HWASAN_SHADOW]] to ptr
; CHECK-NEXT:    [[TMP3:%.*]] = lshr i64 ptrtoint (ptr @x to i64), 56
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i8
; CHECK-NEXT:    [[TMP5:%.*]] = and i64 ptrtoint (ptr @x to i64), 72057594037927935
; CHECK-NEXT:    [[TMP6:%.*]] = lshr i64 [[TMP5]], 4
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[TMP2]], i64 [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[TMP7]], align 1
; CHECK-NEXT:    [[TMP9:%.*]] = icmp ne i8 [[TMP4]], [[TMP8]]
; CHECK-NEXT:    br i1 [[TMP9]], label [[TMP10:%.*]], label [[TMP11:%.*]], !prof [[PROF4]]
; CHECK:       10:
; CHECK-NEXT:    call void @llvm.hwasan.check.memaccess.shortgranules(ptr [[TMP2]], ptr @x, i32 3)
; CHECK-NEXT:    br label [[TMP11]]
; CHECK:       11:
; CHECK-NEXT:    [[TMP12:%.*]] = load i64, ptr @x, align 8
; CHECK-NEXT:    ret i64 [[TMP12]]
;
entry:
  %0 = load i64, ptr @x, align 8
  ret i64 %0
}

define i32 @test_past_end_offset() sanitize_hwaddress {
; NOGLOB-LABEL: define i32 @test_past_end_offset(
; NOGLOB-SAME: ) #[[ATTR0]] {
; NOGLOB-NEXT:  entry:
; NOGLOB-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr @x, i64 4
; NOGLOB-NEXT:    [[TMP0:%.*]] = load i32, ptr [[PTR]], align 4
; NOGLOB-NEXT:    ret i32 [[TMP0]]
;
; CHECK-LABEL: define i32 @test_past_end_offset(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr @__hwasan_tls, align 8
; CHECK-NEXT:    [[TMP1:%.*]] = or i64 [[TMP0]], 4294967295
; CHECK-NEXT:    [[HWASAN_SHADOW:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[HWASAN_SHADOW]] to ptr
; CHECK-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr @x, i64 4
; CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[PTR]] to i64
; CHECK-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 56
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i8
; CHECK-NEXT:    [[TMP6:%.*]] = and i64 [[TMP3]], 72057594037927935
; CHECK-NEXT:    [[TMP7:%.*]] = lshr i64 [[TMP6]], 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP2]], i64 [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP8]], align 1
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i8 [[TMP5]], [[TMP9]]
; CHECK-NEXT:    br i1 [[TMP10]], label [[TMP11:%.*]], label [[TMP12:%.*]], !prof [[PROF4]]
; CHECK:       11:
; CHECK-NEXT:    call void @llvm.hwasan.check.memaccess.shortgranules(ptr [[TMP2]], ptr [[PTR]], i32 2)
; CHECK-NEXT:    br label [[TMP12]]
; CHECK:       12:
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[PTR]], align 4
; CHECK-NEXT:    ret i32 [[TMP13]]
;
entry:
  %ptr = getelementptr i8, ptr @x, i64 4
  %0 = load i32, ptr %ptr, align 4
  ret i32 %0
}

define i32 @test_partial_overflow() sanitize_hwaddress {
; NOGLOB-LABEL: define i32 @test_partial_overflow(
; NOGLOB-SAME: ) #[[ATTR0]] {
; NOGLOB-NEXT:  entry:
; NOGLOB-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr @x, i64 2
; NOGLOB-NEXT:    [[TMP0:%.*]] = load i32, ptr [[PTR]], align 4
; NOGLOB-NEXT:    ret i32 [[TMP0]]
;
; CHECK-LABEL: define i32 @test_partial_overflow(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr @__hwasan_tls, align 8
; CHECK-NEXT:    [[TMP1:%.*]] = or i64 [[TMP0]], 4294967295
; CHECK-NEXT:    [[HWASAN_SHADOW:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[HWASAN_SHADOW]] to ptr
; CHECK-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr @x, i64 2
; CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[PTR]] to i64
; CHECK-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 56
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i8
; CHECK-NEXT:    [[TMP6:%.*]] = and i64 [[TMP3]], 72057594037927935
; CHECK-NEXT:    [[TMP7:%.*]] = lshr i64 [[TMP6]], 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP2]], i64 [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP8]], align 1
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i8 [[TMP5]], [[TMP9]]
; CHECK-NEXT:    br i1 [[TMP10]], label [[TMP11:%.*]], label [[TMP12:%.*]], !prof [[PROF4]]
; CHECK:       11:
; CHECK-NEXT:    call void @llvm.hwasan.check.memaccess.shortgranules(ptr [[TMP2]], ptr [[PTR]], i32 2)
; CHECK-NEXT:    br label [[TMP12]]
; CHECK:       12:
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[PTR]], align 4
; CHECK-NEXT:    ret i32 [[TMP13]]
;
entry:
  %ptr = getelementptr i8, ptr @x, i64 2
  %0 = load i32, ptr %ptr, align 4
  ret i32 %0
}

